# Python Básico para Física Experimental

In [52]:
%matplotlib notebook

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit as fit
from io import StringIO

#data = pd.read_table('data.txt', )

In [55]:
data_text = StringIO('''
x	y	y_err
0.00	-0.12	0.10
0.05	0.16	0.10
0.10	0.20	0.10
0.15	0.15	0.10
0.20	0.13	0.10
0.25	0.14	0.10
0.30	0.21	0.10
0.35	0.08	0.10
0.40	0.44	0.10
0.45	0.45	0.10
0.50	0.56	0.10
0.55	0.60	0.10
0.60	0.55	0.10
0.65	0.56	0.10
0.70	0.72	0.10
0.75	0.79	0.10
0.80	0.81	0.10
0.85	0.88	0.10
0.90	1.09	0.10
0.95	1.03	0.10
1.00	0.87	0.10
''')

In [56]:
data = pd.read_table(data_text)

In [57]:
data

       x     y  y_err
0   0.00 -0.12    0.1
1   0.05  0.16    0.1
2   0.10  0.20    0.1
3   0.15  0.15    0.1
4   0.20  0.13    0.1
5   0.25  0.14    0.1
6   0.30  0.21    0.1
7   0.35  0.08    0.1
8   0.40  0.44    0.1
9   0.45  0.45    0.1
10  0.50  0.56    0.1
11  0.55  0.60    0.1
12  0.60  0.55    0.1
13  0.65  0.56    0.1
14  0.70  0.72    0.1
15  0.75  0.79    0.1
16  0.80  0.81    0.1
17  0.85  0.88    0.1
18  0.90  1.09    0.1
19  0.95  1.03    0.1
20  1.00  0.87    0.1